"""add column name into bunker

Revision ID: aed3a3317805
Revises: 9965c117ae22
Create Date: 2026-03-09 16:37:57.474056

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "aed3a3317805"
down_revision: str | Sequence[str] | None = "9965c117ae22"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bunker", schema="zero")
    op.create_table(
        "bunker",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("product_type", sa.String(), nullable=False),
        sa.Column("max_volume", sa.Integer(), nullable=False, comment="kg"),
        sa.Column("current_volume", sa.Integer(), nullable=False, comment="kg"),
        sa.Column("pre_close_value", sa.Integer(), nullable=False, comment=" kg"),
        sa.Column("name", postgresql.CITEXT(), nullable=False),
        sa.CheckConstraint(
            "length(name) >= 3 AND length(name) <= 32",
            name=op.f("ck_bunker_name_length"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bunker")),
        sa.UniqueConstraint("name", name=op.f("uq_bunker_name")),
        schema="zero",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bunker", schema="zero")
    # ### end Alembic commands ###
