"""init

Revision ID: a91283d4e5be
Revises:
Create Date: 2026-03-09 10:03:46.714254

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a91283d4e5be"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("bunker",
    sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
    sa.Column("product_type", sa.String(), nullable=False),
    sa.Column("max_volume", sa.Integer(), nullable=False, comment="kg"),
    sa.Column("current_volume", sa.Integer(), nullable=False, comment="kg"),
    sa.Column("pre_close_value", sa.Integer(), nullable=False, comment=" kg"),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_bunker")),
    schema="zero"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bunker", schema="zero")
    # ### end Alembic commands ###
